### ISSUE TITLE
主题能否增加一个top按钮？

### ISSUE THREAD

**Issue by harry10086** [shiyiya/typecho-theme-sagiri#14]
主题用着挺好，感觉就差了个top按钮
我自己用插件加了一个，结果图标一点就变成了图片放大了，没有到顶的功能了
能否增加一个呢？
谢谢！

**Comment by shiyiya** [comment]
- 结果图标一点就变成了图片放大了 （我会解决这个问题

**Comment by harry10086** [comment]
> * 结果图标一点就变成了图片放大了 （我会解决这个问题

感谢！
