### ISSUE TITLE
文章缩略图不显示

### ISSUE THREAD

**Issue by caoxicheng** [shiyiya/typecho-theme-sagiri#17]
php：错误信息如下
Warning: in_array() expects parameter 2 to be array, null given in \usr\themes\Sagiri\theme-helper.php on line 353

ps:实在抱歉PHP有些生疏，无法自行解决

**Comment by caoxicheng** [comment]
已经解决，外观主题重新应用一下。

**Comment by caoxicheng** [comment]
在应用外观是出现错误提示
Fatal error: Call to undefined function curl_init() in \usr\themes\Sagiri\theme-helper.php on line 8

**Comment by shiyiya** [comment]
- 临时解决
  - 第一个可能是 你一个选项都没勾选？？
  - 删除 function.php   的以下：
  ```
    $sagiri = new Sagiri();
    $sagiri->update();
    $sagiri->ga();
  ```

**Comment by caoxicheng** [comment]
thk😀
