### ISSUE TITLE
Call to undefined method Sagiri::ga()

### ISSUE THREAD

**Issue by GiriNeko** [shiyiya/typecho-theme-sagiri#19]
![F(C(V}~)FQ XT1M~BPLAXFM](https://user-images.githubusercontent.com/21117880/62129969-8b529200-b30a-11e9-8dee-b41074e2f829.png)

**Comment by shiyiya** [comment]
Delete line 10 of function.php.

**Comment by GiriNeko** [comment]
OK thanks.
