### ISSUE TITLE
友链页面问题

### ISSUE THREAD

**Issue by LazyCreeper** [shiyiya/typecho-theme-sagiri#21]
![73_5WD_227NOPBR~DHO7Z7R.png](https://imgs.lovpass.cn/img/2019/08/07/5d4a45e78d11f.png)
![LKFA_F34B__`QR__FZ_GG_4.png](https://imgs.lovpass.cn/img/2019/08/07/5d4a45edafd1b.png)
我按照Github的指导设置友链，可是就是不行

**Comment by shiyiya** [comment]
这是我的友链写法，你可以参考一下。
```
- ![friend](https://secure.gravatar.com/avatar/06a2950d128ec9faf155e28d9e889baa?s=100&r=G&d)[kotori空樱酱](https://kotori.love/)<hr>ことりのおやつにしてやるぞー！
```

**Comment by LazyCreeper** [comment]
还是不行哦。。
![img](https://i.natfrp.com/a7283797ad1a172e963c2d9bce15eec4.png)
![img](https://i.natfrp.com/421d6b09d909e533ba3e258d0fb2f56b.png)

**Comment by shiyiya** [comment]
新建独立页面选择独立模板（temple of link)！

**Comment by LazyCreeper** [comment]
emm好吧我忘了233，现在可以了
