### ISSUE TITLE
最新版主题PV记录有问题

### ISSUE THREAD

**Issue by LazyCreeper** [shiyiya/typecho-theme-sagiri#30]
从原来的老版本跳到新版本后，博客所有文章浏览量都归零了（使用Access插件在后台还是能看到），但是随便点击一篇文章后，所有的文章浏览量都会+1。

**Comment by shiyiya** [comment]
查看 field.php 内注释

**Comment by LazyCreeper** [comment]
切换到方案B就可以了，肥肠感谢😁

**Comment by Vulpure** [comment]
搜索和分类功能好像还没开发？点击显示0ops
