### ISSUE TITLE
评论排列问题

### ISSUE THREAD

**Issue by MliKiowa** [shiyiya/typecho-theme-sagiri#34]
**Is your feature request related to a problem? Please describe.**
正序时间排列导致最新评论被埋没 
查找最新评论时间较长
不符合操作习惯
**Describe the solution you'd like**
推荐改为倒序时间排列或者可选倒序时间排列

**Describe alternatives you've considered**

**Additional context**

**Comment by shiyiya** [comment]
后台 -> 设置 -> 评论 -> 将  较新的 的评论显示在前面
