### ISSUE TITLE
首页那一栏的🔍图标无效

### ISSUE THREAD

**Issue by Huihao-Yang** [shiyiya/typecho-theme-sagiri#40]
点击🔍图标，会直接跳转404页面
请问有什么办法修复，或者直接删除这个🔍图标吗？

**Comment by shiyiya** [comment]
[readme](https://github.com/shiyiya/typecho-theme-sagiri/blob/master/doc/README-CN.md#%E7%8B%AC%E7%AB%8B%E9%A1%B5%E9%9D%A2)

**Comment by Huihao-Yang** [comment]
![image](https://user-images.githubusercontent.com/57098815/91069720-5711e800-e668-11ea-9427-45359e037263.png)
我说的就自带的🔍搜索图标，点击之后会显示页面没找到

**Comment by shiyiya** [comment]
readme链接有写，那就是搜索页
