### ISSUE TITLE
能否指导一下怎么增加owo自定义表情？

### ISSUE THREAD

**Issue by NOAME18** [shiyiya/typecho-theme-sagiri#41]
readme给的两个链接有点看不懂。
以蛆音娘为例，已经在js/lib/OwO/OwO.json添加了对应部分
![image](https://user-images.githubusercontent.com/53110680/91377338-b2eb9500-e851-11ea-9ae9-634531f9c583.png)
但是我不知道图片文件要放到哪个路径，此外还要改什么地方？

**Comment by shiyiya** [comment]
[参考这个](https://github.com/DIYgod/OwO/blob/master/demo/OwO.json#L272)

**Comment by NOAME18** [comment]
可以了，感谢
