### ISSUE TITLE
手机访问文章，b站视频会失效。

### ISSUE THREAD

**Issue by c2z1314** [shiyiya/typecho-theme-sagiri#43]
在电脑端可以正常加载视频，如下图。
![image](https://user-images.githubusercontent.com/66543249/98460413-2bba8600-21df-11eb-8e5c-97cd8a74a6a7.png)

但是在手机段就会显示失效，如下图。
![image](https://user-images.githubusercontent.com/66543249/98460409-265d3b80-21df-11eb-9616-476fe2f631f4.png)

文章内容如下，用的[bplayer]，这个是b站的bug吗？
![image](https://user-images.githubusercontent.com/66543249/98460435-573d7080-21df-11eb-96f2-4c0ed1c7aa41.png)

**Comment by shiyiya** [comment]
直接用 b 站自带分享的 html 代码吧
