### ISSUE TITLE
文章不支持markdown中的一二三标题显示

### ISSUE THREAD

**Issue by ThisisWilli** [shiyiya/typecho-theme-sagiri#44]
首先非常感谢博主的创作
使用了sagiri主题之后，发现文章不支持markdown中的#.##,###标题显示，最后都是一级标题，请问怎么解决

**Comment by shiyiya** [comment]
支持的，不用解决。

**Comment by ThisisWilli** [comment]
> 支持的，不用解决。

首先感谢回复，之前没表达清楚，文章中标题显示没问题，但是侧边栏的文章目录没有将不同等级的标题逐级显示，而是统一显示成同等级的标题，如下图所示，请问可以解决么
![微信截图_20201121141345](https://user-images.githubusercontent.com/38526639/99869182-f6149480-2c03-11eb-95d5-1a3e8d93b1c6.png)

**Comment by shiyiya** [comment]
兼容某些的第三方富文本，暂时不考虑，如果需要这个功能可以尝试自己实现一下。

**Comment by ThisisWilli** [comment]
> 兼容某些的第三方富文本，暂时不考虑，如果需要这个功能可以尝试自己实现一下。
明白了 谢谢
