### ISSUE TITLE
希望增加一个填写备案号的地方

### ISSUE THREAD

**Issue by YangXiaoguozi** [shiyiya/typecho-theme-sagiri#47]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/61831143/104807674-9f9a8f80-581b-11eb-8b8d-ccdb0b663df4.png)
像这样

**Comment by shiyiya** [comment]
可以直接在 footer.php 加，我认为不太必要添加那么多琐碎并且不是 **必需** 的配置项

**Comment by YangXiaoguozi** [comment]
谢谢大大，搞好了
