### ISSUE TITLE
将cdn.jsdelivr.net换成别的加速方案

### ISSUE THREAD

**Issue by 2096779623** [shiyiya/typecho-theme-sagiri#65]
由于jsfelivr在中国大陆被dns污染了，所以请更换成别的加速方案，比如：https://statically.io

**Comment by shiyiya** [comment]
有空在搞，欢迎 PR

**Comment by shiyiya** [comment]
```
➜  ~ curl https://cdn.statically.io/gh/shiyiya/typecho-theme-sagiri/v1.2.3/gulpfile.js
curl: (28) Failed to connect to cdn.statically.io port 443 after 75015 ms: Operation timed out
```
上海表示无法访问

**Comment by 2096779623** [comment]
> ```
> ➜  ~ curl https://cdn.statically.io/gh/shiyiya/typecho-theme-sagiri/v1.2.3/gulpfile.js
> curl: (28) Failed to connect to cdn.statically.io port 443 after 75015 ms: Operation timed out
> ```
> 
> 上海表示无法访问

https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.2.3/<github 存储库文件>

需要调整一下github存储库的路径

这个速度挺快

@shiyiya

**Comment by 2096779623** [comment]
@shiyiya 
https://npm.sourcegcdn.com/typecho-theme-sagiri@1.2.2/

**Comment by shiyiya** [comment]
https://github.com/shiyiya/typecho-theme-sagiri/releases/tag/v1.3.1
@2096779623 试试

**Comment by 2096779623** [comment]
> https://github.com/shiyiya/typecho-theme-sagiri/releases/tag/v1.3.1 @2096779623 试试

![image](https://user-images.githubusercontent.com/57583560/174483990-1a09f659-2ce3-419b-8812-70a82908072d.png)

边框加载不出来（）
![image](https://user-images.githubusercontent.com/57583560/174484008-5c48ce5e-0956-4dab-b743-d1ea92767e73.png)
OwO没问题了

**Comment by shiyiya** [comment]
什么边框

**Comment by 2096779623** [comment]
> 什么边框

![image](https://user-images.githubusercontent.com/57583560/174484146-882d9e6c-24dc-4d29-8adb-639c97707b80.png)
这是原来的样子

**Comment by shiyiya** [comment]
我这里访问 https://blog.utermux.dev/?utm_source=utermux.dev 是正常的

![image](https://user-images.githubusercontent.com/34017352/174484647-17eb0e50-699f-45d3-866e-e4f0c6bcc204.png)

**Comment by 2096779623** [comment]
> 我这里访问 https://blog.utermux.dev/?utm_source=utermux.dev 是正常的
> 
> ![image](https://user-images.githubusercontent.com/34017352/174484647-17eb0e50-699f-45d3-866e-e4f0c6bcc204.png)

因为我换了（）

**Comment by shiyiya** [comment]
@2096779623 
https://github.com/shiyiya/typecho-theme-sagiri/releases/tag/v1.3.2

**Comment by shiyiya** [comment]
> > ```
> > ➜  ~ curl https://cdn.statically.io/gh/shiyiya/typecho-theme-sagiri/v1.2.3/gulpfile.js
> > curl: (28) Failed to connect to cdn.statically.io port 443 after 75015 ms: Operation timed out
> > ```
> > 上海表示无法访问
> 
> https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.2.3/<github 存储库文件>
> 
> 需要调整一下github存储库的路径
> 
> 这个速度挺快

@2096779623  
![image](https://user-images.githubusercontent.com/34017352/178133606-9b073ed3-c3e1-4761-9833-afc3f9c63e64.png)

这看起来得用 https://gh.sourcegcdn.com/ 这个？
https://github.com/shiyiya/typecho-theme-sagiri/pull/66/commits/f9208694ac1a17d63c98c7a654436a7cc1e510bd#diff-f3818ee6dce52917ea8692a4973fe8ec6e1cbf38ff243e0b195dd9f270308562R10

**Comment by 2096779623** [comment]
> > > ```
> > > ➜  ~ curl https://cdn.statically.io/gh/shiyiya/typecho-theme-sagiri/v1.2.3/gulpfile.js
> > > curl: (28) Failed to connect to cdn.statically.io port 443 after 75015 ms: Operation timed out
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 上海表示无法访问
> > 
> > 
> > https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.2.3/<github 存储库文件>
> > 需要调整一下github存储库的路径
> > 这个速度挺快
> 
> @2096779623 ![image](https://user-images.githubusercontent.com/34017352/178133606-9b073ed3-c3e1-4761-9833-afc3f9c63e64.png)
> 
> 这看起来得用 https://gh.sourcegcdn.com/ 这个？ [f920869#diff-f3818ee6dce52917ea8692a4973fe8ec6e1cbf38ff243e0b195dd9f270308562R10](https://github.com/shiyiya/typecho-theme-sagiri/commit/f9208694ac1a17d63c98c7a654436a7cc1e510bd#diff-f3818ee6dce52917ea8692a4973fe8ec6e1cbf38ff243e0b195dd9f270308562R10)

![image](https://user-images.githubusercontent.com/57583560/178135495-1711982d-9b86-4e42-b238-b486ef81946a.png)

**Comment by shiyiya** [comment]
![image](https://user-images.githubusercontent.com/34017352/178136478-a1ce0ef1-c8bf-413a-a849-0b891930f175.png)

https://github.com/shiyiya/typecho-theme-sagiri/commit/f9208694ac1a17d63c98c7a654436a7cc1e510bd#diff-f3818ee6dce52917ea8692a4973fe8ec6e1cbf38ff243e0b195dd9f270308562R10

**Comment by 2096779623** [comment]
> > > > ```
> > > > ➜  ~ curl https://cdn.statically.io/gh/shiyiya/typecho-theme-sagiri/v1.2.3/gulpfile.js
> > > > curl: (28) Failed to connect to cdn.statically.io port 443 after 75015 ms: Operation timed out
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 上海表示无法访问
> > > 
> > > 
> > > https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.2.3/<github 存储库文件>
> > > 需要调整一下github存储库的路径
> > > 这个速度挺快
> > 
> > 
> > @2096779623 ![image](https://user-images.githubusercontent.com/34017352/178133606-9b073ed3-c3e1-4761-9833-afc3f9c63e64.png)
> > 这看起来得用 https://gh.sourcegcdn.com/ 这个？ [f920869#diff-f3818ee6dce52917ea8692a4973fe8ec6e1cbf38ff243e0b195dd9f270308562R10](https://github.com/shiyiya/typecho-theme-sagiri/commit/f9208694ac1a17d63c98c7a654436a7cc1e510bd#diff-f3818ee6dce52917ea8692a4973fe8ec6e1cbf38ff243e0b195dd9f270308562R10)
> 
> ![image](https://user-images.githubusercontent.com/57583560/178135495-1711982d-9b86-4e42-b238-b486ef81946a.png)

![image](https://user-images.githubusercontent.com/57583560/178136567-8577c931-f281-42cc-9c4b-f04236fde703.png)

**Comment by shiyiya** [comment]
我看这里回复的是用 gh.sourcegcdn.com ， 你的pr是 npm.sourcegcdn。 
我这里试了 npm 是下载的头，gh 是可用。 所以应该是？

**Comment by 2096779623** [comment]
> 我看这里回复的是用 gh.sourcegcdn.com ， 你的pr是 npm.sourcegcdn。 我这里试了 npm 是下载的头，gh 是可用。 所以应该是？

gh不可用，返回HTTP CODE 424，npm返回下载头。
我找站长说说

**Comment by shiyiya** [comment]
gh 我没了打 1.3 的 tag， v1.2.3 是有的。

**Comment by 2096779623** [comment]
> gh 我没了打 1.3 的 tag， v1.2.3 是有的。

![image](https://user-images.githubusercontent.com/57583560/178137339-26b15247-ba06-4ec1-b27a-afebde9b9bf2.png)

**Comment by shiyiya** [comment]
https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.2.3/css/mix.min.css
https://npm.sourcegcdn.com/@bylin/typecho-theme-sagiri@1.2.3/css/mix.min.cs

**Comment by 2096779623** [comment]
> 



> https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.2.3/css/mix.min.css https://npm.sourcegcdn.com/@bylin/typecho-theme-sagiri@1.2.3/css/mix.min.cs

css没有问题，就是js会炸

> 需要调整一下github存储库的路径

**Comment by shiyiya** [comment]
那种可用用哪种吧~  反正是同一个 cdn

**Comment by shiyiya** [comment]
npm 会有问题那换成 gh 了？

**Comment by 2096779623** [comment]
> npm 会有问题那换成 gh 了？

先等等

> 需要调整一下github存储库的路径

**Comment by shiyiya** [comment]
@2096779623

**Comment by 2096779623** [comment]
> @2096779623

![image](https://user-images.githubusercontent.com/57583560/178276783-c554e13c-d532-42bc-acae-f7e1aa061cf4.png)

**Comment by shiyiya** [comment]
https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.3.4/css/mix.min.css
https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.3.4/css/mix.css
https://cdn.jsdelivr.net/npm/@bylin/typecho-theme-sagiri@1.3.4/css/mix.min.css

这是 min 返回了非 min，然后塞了东西啊....

**Comment by AH-dark** [comment]
> https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.3.4/css/mix.min.css https://gh.sourcegcdn.com/shiyiya/typecho-theme-sagiri/v1.3.4/css/mix.css https://cdn.jsdelivr.net/npm/@bylin/typecho-theme-sagiri@1.3.4/css/mix.min.css
> 
> 这是 min 返回了非 min，然后塞了东西啊....

关于这个我会优化的，主要是回源优先级问题。
