### ISSUE TITLE
php8会出现Deprecated:Required parameter $content follows optional parameter ShasLogin in的问题

### ISSUE THREAD

**Issue by longdaiquan** [shiyiya/typecho-theme-sagiri#70]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shiyiya** [comment]
可以定位到具体位置么？建议截图错误

**Comment by longdaiquan** [comment]
解决了解决了，这个代码出现的位置大概在主页图片的左下角
我参照了这张图片，https://s3.bmp.ovh/imgs/2022/08/02/218c21118f281cec.png
交换了下这里的位置：https://s3.bmp.ovh/imgs/2022/08/02/43a5ecb557789bd7.png
