### ISSUE TITLE
1.3.4版本主题无法在Typecho 1.2.0上使用

### ISSUE THREAD

**Issue by LazyCreeper** [shiyiya/typecho-theme-sagiri#71]
**Describe the bug**
Typecho `v1.2.0`无法使用1.3.4版本主题

**To Reproduce**
1. 从`release`页面下载
2. 上传到网站目录
3. 登录Typecho后台，选择外观Sagiri，启用
4. 显示`您选择的风格不存在`

**Screenshots**
![联想截图_20230129204958.png](https://s2.loli.net/2023/01/29/yRtm71nhwajHglI.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser: Chrome 
 - Version 109.0.5414.75

**Additional context**
 - BT-Panel
 - NGINX-Tegine 2.2.4
 - PHP-7.4.33
 - MySQL 8.0.24

**Comment by shiyiya** [comment]
1.2是新版还是旧版？

**Comment by shiyiya** [comment]
用1.22就行了 后面只是更新了一下依赖
很久没搞这个了 你可以试试PR一下😂

**Comment by LazyCreeper** [comment]
OK，主题已经滚回1.2.2版本了，php降级到7.2、typecho降级到1.1、mysql降到5.7。运行正常

**Comment by shiyiya** [comment]
define('__TYPECHO_DEBUG__', true);

周末我看看吧

**Comment by shiyiya** [comment]
@LazyCreeper 我这里一切正常啊 (→_→)

php 7.4.3-nts
mysql 8.0.12

ps: 主题文件夹名字 typecho-theme-sagiri
